Add visual snapshot testing
depapp/IndoGitHubers pull request #92
Opened 2024-12-04 04:46 UTC by ImBIOS

Fix #74

2024-12-04 04:57 UTC, ImBIOS commented
wait... it's to tiny to be single PR, I'm attempting to address all the task under the "umbrella"

2024-12-04 06:16 UTC, mazipan requested changes

2024-12-04 06:16 UTC, mazipan commented on tests/home.spec.ts
>        });
Is it better to add another step to assert the visual?

Something like this:
```suggestion
     await test.step('Then validate visual for search result', async () => {
        await expect(page).toHaveScreenshot('search-results-valid.png', { maxDiffPixelRatio: 0.02 });
     ]})
```

cc: @depapp

2024-12-05 01:35 UTC, depapp reviewed
thanks for the PR mas @ImBIOS 🙇🏻 

anyway, since this visual testing will use the baseline from the `__screenshots__` directory, and we might have different operating systems (which could affect the appearance of the 🥇🥈🥉 icons), would it be better to ignore the directory?
wdyt mas @ImBIOS & mas @mazipan ?

2024-12-05 02:34 UTC, mazipan commented
In the CI, we will generate the baseline snapshot using Ubuntu.
So the approach is usually by running the test inside ubuntu docker for local development.

2024-12-07 11:46 UTC, mazipan commented
To appreciate the effort, how if we merge this one.
And I will work on this visual test later.
@depapp

2024-12-08 08:59 UTC, depapp commented
> To appreciate the effort, how if we merge this one.
> And I will work on this visual test later.

sure, I agree. approved

2024-12-08 08:59 UTC, depapp approved these changes

2024-12-09 04:47 UTC, merged